### PR TITLE
Store start inside the Lexer struct

### PR DESCRIPTION
**Pull request by est31**
This way, start doesn't have to be passed around as much.

### CODE REVIEW

**Comment by calixteman** [comment]
I don't understand what's the goal here.
The start location is created before we get the next token and then moved in the returned token.
Is there any reason to save this value ? 
If it's only a cosmetic change then the macro loc! can be moved inside the loop:
```rust
macro_rules! loc {
    ($tok: expr) => {{
        LocToken::new($tok, self.buf.get_source_id(), start, self.location())
    }};
}
```
just after start creation.
I'd prefer avoiding useless operations except if there is a good rational.

**Comment by est31** [comment]
@calixteman it's needed by #6 : https://github.com/calixteman/rust-cpp-parser/pull/6/files#diff-ef934c194289cb739277c4d5b3446f31R174

The span here uses the internally stored start. Otherwise I'd have to pass start to the preprocessor and any other place that might create an error. Do you want that instead?

**Comment by calixteman** [comment]
I think I understand your point.
Please add a todo comment close the start definition, just to tell something like "performance matters so see how we can get rid of that".
And I'll merge your pr.

**Comment by est31** [comment]
@calixteman I've updated it.

**Comment by calixteman** [comment]
I thought that it was a bad idea but maybe it's finally a good one.
My concern was that we store the start location two times: one in the lexer and one in the LocToken so one is probably redundant.
I think that most of the time the location is useless in a token so probably having it in the parser and get it when needed only is probably better.
So I'll make a commit to remove LocToken and I'll merge that stuff after.

**Comment by calixteman** [comment]
merged: https://github.com/calixteman/rust-cpp-parser/commit/e6397d0dcb5c5583e03ed3804e2b9f0f43d8b2b6

**Pull request closed without merging**
