### PR TITLE
Fix or allow clippy lints and rustc warnings

### PR DESCRIPTION
**Pull request by est31**

### CODE REVIEW

**Comment by est31** [comment]
Now both `cargo clippy` and `cargo check` don't complain.

**Comment by est31** [comment]
Hmm no a test fails. It doesn't work... Lemme split up the change into separate commits...

**Comment by est31** [comment]
Tests pass... ready for review @calixteman 

The only clippy lints remained unfixed regard the transmutes. Tried to resolve them but got test failures.

**Comment by calixteman** [comment]
thx

**Pull request merged**
